### ISSUE TITLE
fswatch (inotify) does not track newly created dirs recursively

### ISSUE THREAD

**Issue by Spiritdude** [emcrisostomo/fswatch#114]
On Linux (Ubuntu 15.10):

% fswatch -drx ./
% mkdir a
% cd a; touch zz.txt

No notification of zz.txt is happening, but creation of dir a/ is happening.

**Comment by emcrisostomo** [comment]
Bug acknowledged.

**Comment by emcrisostomo** [comment]
Hi @Spiritdude,

This should be fixed in the `<develop>` branch.  Would you mind testing it? It will take me some days to rebuild and test `fswatch` in all the supported platforms.

**Comment by Spiritdude** [comment]
I just tested it briefly:
1) created new dir xx/, ok
2) created new file xx/aa.txt, ok
3) created new dir xx/yy/, ok
4) created new file xx/yy/bb.txt, ok

:-) so it seems fixed, thanks!

**Comment by Spiritdude** [comment]
Perhaps close issue when the fix is in the main branch available.

**Comment by emcrisostomo** [comment]
Thanks @Spiritdude for testing this one!

I think we can close this: the _milestone_ tag (`1.9.0`) specifies the release that will include this fix.

**Comment by damscal** [comment]
I'm still experiencing this bug with the current ubuntu's package

**Comment by YujiShen** [comment]
Same problem when using inotify on Ubuntu 18.04, (fswatch version 1.11.2). poll_monitor does not have this problem, but it report all files under the new folder instead of only report the folder.
